name = "DBJpack-neoforge"
author = "doublej472"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bb742c6c693e5e2b9213ae37f9ba4e10220b2396faa209dc9e5aa39d7cbe25d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.100"
