name = "DBJpack"
author = "doublej472"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9116f417fde3b096215d4cee7d336f8e3b4cbc8434ed40618419e48f8d31dda"

[versions]
minecraft = "1.20.1"
quilt = "0.21.1"
