name = "DBJpack"
author = "doublej472"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb70ef8753a32ff8827a4312fd477cc7d32a3dc0d66a5851351cbb8e5368e62a"

[versions]
minecraft = "1.20.1"
quilt = "0.21.1"
