name = "DBJpack"
author = "doublej472"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a93b429f8b8acfec69537a9a4cf2f05253291b73f6c884a72d694f0ce413b324"

[versions]
minecraft = "1.20.1"
quilt = "0.19.5"
