name = "DBJpack"
author = "doublej472"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c86aa2f6428d24daedd46d1206f3a9816ae231fac8dcd469591b1083c4ebf127"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
