name = "DBJpack-neoforge"
author = "doublej472"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdfb7f7ba09edd5392ff5edb8d0b4dbf0ef99ec92272bac88282e39f1a614a56"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.100"
