name = "DBJpack"
author = "doublej472"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cc244dfcd7a9c5feed7131f1ef237e88bf8bfcbaf640a4eb20dc0851654381a"

[versions]
minecraft = "1.20.1"
quilt = "0.19.5"
