name = "DBJpack"
author = "doublej472"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "501b6dcc1e2525f47f3c778dae03a137fe37b2695c33be22e902244cd0363bd5"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
